### ISSUE TITLE
You could delete build.js from the github

### ISSUE THREAD

**Issue by ro-pardo** [ParallelHierarchies/ParallelHierarchies#1]
Hi guys, nice job.
I update the var CONFIGURATION in app.js for my own custom input and doesn't affect directly the inputs files available. That was solved when I regenerate the build.js with npm.
Maybe you should delete that file from the github and add that step on the read me, to avoid misunderstandings.
Thanks you for your work!

**Comment by Mahog** [comment]
Hi, 
thanks for your comment and sorry for the delay in following up. 

I have now added a section on developing Parallel Hierarchies to the README. We will keep the bundle.js in the repository in order to get people started immediately after cloning the project without the need to install node first. We will also clarify this in the "using your own data" section on the project website.
